version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: energia
      MYSQL_USER: energia_user
      MYSQL_PASSWORD: energia_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
